version: '3'
services:
############# container ##########
  nginx:
    image: nginx:alpine
    labels:
      - "traefik.frontend.rule=Host:marcoreitano.dev,www.marcoreitano.dev"

############# traefik ############
  traefik:
    image: traefik
    command: --api --docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
          - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: containous/whoami # A container that exposes an API to show its IP address
    labels:
      - "traefik.frontend.rule=Host:whoami.marcoreitano.dev"

############# Keycloak ###########
  keycloak:
    image: jboss/keycloak
    ports:
      - 8098:8080
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - PROXY_ADDRESS_FORWARDING=true

############## KAFKA ##############
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - 5000:5000
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:5000
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

############### ARTIST MS ##############
#  artist:
#    image: marcoreitano/artist:latest
#    ports:
#      - 8080:8080
#
############### VENUE-MS ################
#  venue:
#    image: marcoreitano/venue:latest
#    ports:
#      - 8081:8081
#
############### CONCERT MS ##############
#  concert:
#    image: marcoreitano/concert:latest
#    ports:
#      - 8082:8082
