version: "3.2"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - type: bind
        source: ./elements
        target: /usr/share/nginx/html
networks:
  default:
    external:
      name: webcomponents

